services:

  backend:
    build: ./innovatech-backend
    container_name: innovatech-backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: innovatech_db

  frontend:
    build: ./innovatech-frontend
    container_name: innovatech-frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: innovatech-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovatech_db

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: