name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen Backend
        run: docker build -t chilindrina/innovatech-backend:latest ./innovatech-backend

      - name: Construir imagen Frontend
        run: docker build -t chilindrina/innovatech-frontend:latest ./innovatech-frontend

      - name: Publicar Backend en Docker Hub
        run: docker push chilindrina/innovatech-backend:latest

      - name: Publicar Frontend en Docker Hub
        run: docker push chilindrina/innovatech-frontend:latest

      - name: Validar Docker Compose
        run: docker compose config